# 规则文件配置
groups:
  - name: example
    # 规则组的名称，用于标识一组规则
    rules:
      # 告警规则：当某个实例不可达超过1分钟时触发告警
      - alert: InstanceDown
        # 告警的名称，用于标识特定的告警条件
        expr: up == 0
        # 表达式，定义了触发告警的条件
        # 在这个例子中，当 `up` 指标的值为 0 时，表示实例不可达
        for: 1m
        # 告警持续时间，实例不可达状态需要持续 1 分钟才会触发告警
        labels:
          severity: page
          # 标签，用于分类和过滤告警
          # `severity` 标签通常用于表示告警的严重程度，例如 "page" 表示需要立即关注
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          # 摘要，用于简要描述告警信息 使用 Go 模板语法 `{{ $labels.instance }}` 动态插入实例名称
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
          # 描述，用于详细描述告警信息 `{{ $labels.instance }}` 和 `{{ $labels.job }}` 动态插入实例名称和作业名称

      # 告警规则：当 Spring Boot 应用的内存使用率超过 80% 时触发告警
      - alert: HighMemoryUsage
        expr: process_memory_max_bytes{application="my-spring-boot-app"} * 0.8 < process_memory_resident_bytes{application="my-spring-boot-app"}
        # 表达式，定义了触发告警的条件
        # 在这个例子中，当 `process_memory_resident_bytes` 超过 `process_memory_max_bytes` 的 80% 时，表示内存使用率过高
        for: 5m
        # 告警持续时间，内存使用率超过 80% 的状态需要持续 5 分钟才会触发告警
        labels:
          severity: warning
          # 标签，用于分类和过滤告警
          # `severity` 标签通常用于表示告警的严重程度，例如 "warning" 表示警告
        annotations:
          summary: "High memory usage on {{ $labels.application }}"
          # 摘要，用于简要描述告警信息 使用 Go 模板语法 `{{ $labels.application }}` 动态插入应用名称
          description: "The memory usage of {{ $labels.application }} has exceeded 80% for more than 5 minutes."
          # 描述，用于详细描述告警信息 `{{ $labels.application }}` 动态插入应用名称

      # 告警规则：当 Spring Boot 应用的 CPU 使用率超过 80% 时触发告警
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total{application="my-spring-boot-app"}[5m]) * 100 > 80
        # 表达式，定义了触发告警的条件 当 `process_cpu_seconds_total` 的 5 分钟速率超过 80% 时，表示 CPU 使用率过高
        for: 5m
        # 告警持续时间，CPU 使用率超过 80% 的状态需要持续 5 分钟才会触发告警
        labels:
          severity: warning
          # 标签，用于分类和过滤告警 `severity` 标签通常用于表示告警的严重程度，例如 "warning" 表示警告
        annotations:
          summary: "High CPU usage on {{ $labels.application }}"
          # 摘要，用于简要描述告警信息 使用 Go 模板语法 `{{ $labels.application }}` 动态插入应用名称
          description: "The CPU usage of {{ $labels.application }} has exceeded 80% for more than 5 minutes."
          # 描述，用于详细描述告警信息 `{{ $labels.application }}` 动态插入应用名称