version: '3'

services:
#   ollama:
#     container_name: bruce-ollama
#     image: ollama/ollama
#     volumes:
#       - /opt/ollama:/root/.ollama
#       - /opt/ollama/models:/data/models
#     environment:
#       - TZ=Asia/Shanghai
#     ports:
#       - "11434:11434"
#     networks:
#       - public

  open-webui:
    container_name: bruce-open-webui
    image: m.daocloud.io/ghcr.io/open-webui/open-webui:main
    volumes:
      - /opt/open-webui:/app/backend/data
    ports:
      - "3000:8080"
    environment:
      - TZ=Asia/Shanghai
      - 'OLLAMA_BASE_URL=http://192.168.3.7:11434'
      - 'HF_ENDPOINT=https://hf-mirror.com'
    networks:
      - public

networks:
  public:

